---
- name: Create deployment directory
  file:
    path: /opt/example
    state: directory
    owner: ec2-user
    group: ec2-user

- name: Create virtual environment
  command: python3 -m venv /opt/example/venv

- name: Copy application wheel file to the target host
  copy:
    src: files/{{ wheel_file }}
    dest: /opt/example/{{ wheel_file }}
    mode: '0644'    

- name: Install the application
  pip:
    virtualenv: /opt/example/venv
    name: /opt/example/{{ wheel_file }} 

- name: Create instance directory
  file:
    path: /opt/example/instance
    state: directory

- name: Deploy config.py
  template:
    src: config.py.j2
    dest: /opt/example/instance/config.py

- name: Deploy run.sh
  template:
    src: run.sh.j2
    dest: /opt/example/run.sh
    mode: '0755'

- name: Create example.service systemd unit file from template
  template:
    src: example.service.j2
    dest: /etc/systemd/system/example.service
  notify: restart example.service

